### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by misabiko** [WaniKani/Chrome-Notification#3]
When I press save in the option page after entering my API key nothing happens. When looking on the console I get:

> XMLHttpRequest cannot load https://www.wanikani.com/api/v1.1/user/b29...[My API key]...a3e/study-queue. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://oolkffcgenmpgkfknfjfkhgbdnkobnga' is therefore not allowed access.

**Comment by dguenther** [comment]
I updated the extension to support the latest version of the WaniKani API and couldn't repro this issue. Could you confirm if you're still running into it?

**Comment by misabiko** [comment]
The extension appears to be working just fine, it saves almost instantly. Thanks for coming back on this one.

**Comment by dguenther** [comment]
Glad I was able to. Feel free to file new issues if you encounter any more bugs.
